### ISSUE TITLE
Incompatibility with CDI spec

### ISSUE THREAD

**Issue by asbachb** [xlate/jsonapi-rvp#165]
I tried to put that example of the project in a simple web application and deployed it in wildfly 30.

The deployment failed due the lack of a no-arg constructor in class `TransactionalValidator`.

```
Caused by: org.jboss.weld.exceptions.UnproxyableResolutionException: WELD-001435: Normal scoped bean class io.xlate.jsonapi.rvp.internal.validation.boundary.TransactionalValidator is not proxyable because it has no no-args constructor - Managed Bean [class io.xlate.jsonapi.rvp.internal.validation.boundary.TransactionalValidator] with qualifiers [@Any @Default].
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.bean.proxy.DefaultProxyInstantiator.validateNoargConstructor(DefaultProxyInstantiator.java:51)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.util.Proxies.getUnproxyableClassException(Proxies.java:255)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.util.Proxies.getUnproxyableTypeException(Proxies.java:203)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:398)
	... 13 more
```

**Comment by MikeEdgar** [comment]
Hi @asbachb , thanks for reporting this. Do you have bean validation provided as a dependency of your application?

**Comment by asbachb** [comment]
The demo app does just depends on jakartaee-api and jsonapi-rvp.
From my understanding wildly 30 full profile should provide an implementation of the bean validation spec.

**Comment by MikeEdgar** [comment]
> From my understanding wildfly 30 full profile should provide an implementation of the bean validation spec.

Yes, you're right. I would have expected it to work since the `TransactionalValidator` has an `@Inject`-annotated constructor [1]. Do you have the example project share publicly somewhere I can review it?

[1] https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#bean_constructors

**Comment by asbachb** [comment]
I'll add the sample project. Basically I created a plain project and copied the classes in your example.

Also found in spec:

> The container uses proxies to provide certain functionality. Certain legal bean types cannot be proxied by the container:
> 
> * classes which don’t have a non-private constructor with no parameters,
> 
> 

https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#unproxyable

**Comment by asbachb** [comment]
more resources: https://github.com/jakartaee/cdi/issues/464
